### PR TITLE
Optimize logo for darkmode and add logos to assets folder

### PR DESCRIPTION
**Pull request by oberrich**
GitHub has recently added an option to [control images based on light/dark color mode](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#specifying-the-theme-an-image-is-shown-to) using the `<picture>` element.

This PR adds the relevant HTML to README and provides a dark/light mode logo under the `assets/img` folder. Shipping the logos adds around 6KB to the repo, load time should stay the same as the logo is currently also served through githubusercontent.com

### CODE REVIEW

**Comment by athre0z** [comment]
Awesome! This has always annoyed me and I didn't expect it to be possible to fix it. Thanks for taking care of this! :)

**Review by athre0z — APPROVED** [review]

**Comment by flobernd** [comment]
Nice, didn't know about this new feature.

If we ever add an organization README, let's remember to include our new Zyan logos the same way 🙂

**Comment by flobernd** [comment]
image

The iOS app sadly seems to have problems supporting the svg.

**Comment by athre0z** [comment]
This was already an SVG previously though.

**Comment by flobernd** [comment]
In this case, it's the new feature that's not supported. I might report that bug if I find out where 😋

**Comment by oberrich** [comment]
> In this case, it's the new feature that's not supported. I might report that bug if I find out where 😋

Maybe it's an issue with relative paths or it just doesn't support the HTML tags/prefers-color-scheme yet.

**Comment by oberrich** [comment]
@flobernd I have made a branch with absolute paths on my fork: https://github.com/oberrich/zydis/blob/logo-darkmode-abspath/README.md

**Comment by flobernd** [comment]
The absolute path indeed seems to work!

**Pull request merged**
