### PR TITLE
Added /MT and /MTd support

### PR DESCRIPTION
**Pull request by HoShiMin**
Added /MT and /MTd support
Splitted output release/debug folders
Added Visual Studio 2019 support
Fixed files hierarchy

### CODE REVIEW

**Comment by HoShiMin** [comment]
So, let's check it.
I have no idea how to make the DLL buildable with LibC and /MT(d) support, so I made DLL with /MT + ZYAN_NO_LIBC flag.

**Comment by flobernd** [comment]
Hi there, thanks for the PR. Would you mind including the suggested changes from [here](https://github.com/zyantific/zydis/issues/97#issuecomment-469041757)?

**Comment by HoShiMin** [comment]
Oh, sure, I'll try it for a 2-3 days (or at the end of week...), I'll respond you about results!

**Comment by HoShiMin** [comment]
Well, @Mattiwatti was right, removing _DLL and _LIB is a solution. So, it is a final commit I think. So, let's merge it!

**Comment by flobernd** [comment]
Thanks! I'll test it in a minute.

**Comment by flobernd** [comment]
I see that the Platform Toolset v142 seems to be required now. Supporting VS2019 is great, but the project should still be backwards compatible to VS2017. Could you please fix this, before I merge?

**Comment by HoShiMin** [comment]
Oh... I have no installed VS2017 to change it to v141... Can you do it yourself? Or I can, but on weekend

**Comment by flobernd** [comment]
> Can you do it yourself

Yes, I'll have a look.

**Comment by HoShiMin** [comment]
Wow, I can install vs141 to vs2019! So, I can change it myself! If you not start to fix it, I'll do it

**Comment by flobernd** [comment]
> Wow, I can install vs141 to vs2019! So, I can change it myself! If you not start to fix it, I'll do it

All good, I'm currently modifying your PR to fix the toolset. 

And I decided to flaten the output pathes a bit. Instead of `\bin\x86\um\release` it's now just `\bin\ReleaseX86` for example (or `\bin\ReleaseX86Kernel` for the kernel configuration).

Just refactoring some minor things before I will merge your PR.

**Pull request merged**
