### PR TITLE
add -fPIC option for gcc

### PR DESCRIPTION
**Pull request by sincoder**
make zydis easy used in shared object

### CODE REVIEW

**Comment by flobernd** [comment]
CMake should automatically set the `-fPIC` parameter, if you use the `ZYDIS_BUILD_SHARED_LIB` option. It did for me at least ..

**Comment by sincoder** [comment]
@flobernd  But it only create libZydis.so file , if our shard object want static link to libZydis.a , still not possible

**Comment by flobernd** [comment]
Ah, I understand .. so you have a shared library project that you want to link against a static Zydis lib.

Let us check, if there are any drawbacks with forcing position independent code. If not, we can probably add a CMake option for your PR.

**Comment by athre0z** [comment]
CMake has an [`CMAKE_POSITION_INDEPENDENT_CODE`](https://cmake.org/cmake/help/v3.14/variable/CMAKE_POSITION_INDEPENDENT_CODE.html) option to force PIC for all targets. Also check [this response](https://github.com/zyantific/zydis/issues/46#issuecomment-404314617) in a similar issue.

**Comment by flobernd** [comment]
Are you using FreeBSD as well @sincoder?

**Comment by flobernd** [comment]
We decided to not generally force PIC for all build configurations, as it might have negative impact on some platforms and might not be supported on other ones.

As a workaround we suggest you to set the `POSITION_INDEPENDENT_CODE ` property in your projects CMakeFile.txt for both Zycore and Zydis:
```cmake
target_link_libraries("MyProject" PUBLIC "Zydis")

...

set_property(TARGET "Zycore" PROPERTY POSITION_INDEPENDENT_CODE ON)
set_property(TARGET "Zydis" PROPERTY POSITION_INDEPENDENT_CODE ON)
```

**Comment by jessielesbian** [comment]
hi!

**Pull request closed without merging**
