### PR TITLE
Fix issue with `llvm-rc` when `ZYDIS_BUILD_SHARED_LIB` is enabled

### PR DESCRIPTION
**Pull request by netadr**
In addition to the changes mentioned in zyantific/zycore-c#70, this changes the encoding of `resources/VersionInfo.rc` from UTF-16LE to UTF-8 as `clang`'s preprocessor does not support UTF-16.

### CODE REVIEW

**Review by flobernd — COMMENTED** [review]
Thanks for the PR!

Shouldn't we replace the copyright sign here as well?

I merged your change in zycore-c. Maybe you could update the submodule to the latest version as well in this PR.

**Comment by netadr** [comment]
> Shouldn't we replace the copyright sign here as well?

I changed it already here as well.

Sorry, GitHub doesn't do a great job of showing this due to the encoding change, maybe I should have clarified!

**Comment by flobernd** [comment]
@netadr Oh, my bad. I even clicked on "view file", but GitHub seems to show me the old version.

Do you want to update the zycore-c submodule in this PR? We can do this in a later step as well, if that's more comfortable for you.

**Comment by netadr** [comment]
> Do you want to update the zycore-c submodule in this PR? We can do this in a later step as well, if that's more comfortable for you.

@flobernd *Should* be fixed now!

**Review by flobernd — APPROVED** [review]
Looks good! Thanks again.

**Review by athre0z — APPROVED** [review]
👍

**Pull request merged**
