### PR TITLE
Allow doxygen generation to be conditional

### PR DESCRIPTION
**Pull request by ZehMatt**

### CODE REVIEW

**Review by athre0z — APPROVED** [review]
LGTM, thanks!

**Comment by Tachi107** [comment]
Note: the documentation could be disabled already, by passing [`-DCMAKE_DISABLE_FIND_PACKAGE_Doxygen=true`](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html)

**Comment by athre0z** [comment]
Yeah, but the discoverability isn't great with that one. Most people aren't CMake experts and would likely never find this switch. With a dedicated option, it is immediately obvious how to disable it since it shows up in the CMake GUI (which I'd assume is probably what most people use, particularly on Windows).

**Comment by Tachi107** [comment]
True. I became aware of that option just a few weeks ago, but I thought that it could be useful to know for you too :)

**Pull request merged**
